[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api_server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10